language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
script:
  - pnpm run lint
  - pnpm test
  - pnpm run test:coverage
